databaseChangeLog:
  - changeSet:
      id: create_user_security_table
      author: Rohtash Lakra
      context: v0.0.1
      preConditions:
        not:
          tableExists:
            tableName: user_security
        onFail: MARK_RAN
        onFailureMessage: "Table [user_security] already exists."
      changes:
        - createTable:
            tableName: user_security
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    primaryKeyName: pk_user_security_id
                    unique: true
                    uniqueConstraintName: uk_user_security_id
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: platform
                  type: VARCHAR(64)
                  constraints:
                    nullable: false
              - column:
                  name: device_token
                  type: VARCHAR(128)
                  constraints:
                    nullable: false
              - column:
                  name: hashed_token
                  type: VARCHAR(128)
                  constraints:
                    nullable: false
              - column:
                  name: salt
                  type: VARCHAR(128)
                  constraints:
                    nullable: false
              - column:
                  name: expired_at
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: social_identity
                  type: JSON
              - column:
                  name: metadata
                  type: JSON
              - column:
                  name: created_on
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: DATETIME
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: VARCHAR(64)
                  constraints:
                    nullable: false
              - column:
                  name: updated_on
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: DATETIME
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: VARCHAR(64)
                  constraints:
                    nullable: false

        - addForeignKeyConstraint:
            baseTableName: user_security
            baseColumnNames: user_id
            constraintName: fk_users_user_security
            referencedTableName: users
            referencedColumnNames: id

      rollback:
        - noRollback: true

  - changeSet:
      id: create_index_on_user_security_table
      author: Rohtash Lakra
      context: v0.0.1
      preConditions:
        tableExists:
          tableName: user_security
      onFail: MARK_RAN
      onFailureMessage: "Table [user_security] doesn't exist"
      changes:
        - createIndex:
            tableName: user_security
            indexName: idx_user_security_table_user_id
            columns:
              - column:
                  name: user_id

      rollback:
        - noRollback: true

